/*
# Update Small Wins - Practical Independent Living Focus

## Purpose
Remove non-UK relevant tasks and potentially triggering mental health content.
Replace with practical independent living skills focused on:
- Basic self-care (hygiene, sleep, eating)
- UK-specific financial management
- Practical household tasks
- Simple social interactions
- Life skills learning
- Basic health maintenance

## Changes
- Remove tasks not relevant to UK (e.g., bottle deposits)
- Remove potentially triggering mental health tasks
- Add more practical independent living tasks
- Keep language simple, clear, and non-judgmental
- Focus on actionable, concrete tasks
*/

-- Clear existing data
TRUNCATE small_wins CASCADE;

-- Reset the sequence
ALTER SEQUENCE small_wins_id_seq RESTART WITH 1;

-- Insert practical self-care tasks (200 items)
INSERT INTO small_wins (title, category) VALUES
('Drink a glass of water', 'self-care'),
('Brush your teeth', 'self-care'),
('Wash your face', 'self-care'),
('Have a shower', 'self-care'),
('Put on clean clothes', 'self-care'),
('Comb your hair', 'self-care'),
('Put on deodorant', 'self-care'),
('Wash your hands', 'self-care'),
('Take your medication', 'self-care'),
('Eat breakfast', 'self-care'),
('Eat lunch', 'self-care'),
('Eat dinner', 'self-care'),
('Have a snack', 'self-care'),
('Drink some water', 'self-care'),
('Make a cup of tea', 'self-care'),
('Eat a piece of fruit', 'self-care'),
('Eat a vegetable', 'self-care'),
('Make your bed', 'self-care'),
('Open a window for fresh air', 'self-care'),
('Go outside for 5 minutes', 'self-care'),
('Take a short walk', 'self-care'),
('Stretch for 2 minutes', 'self-care'),
('Do 5 jumping jacks', 'self-care'),
('Walk up and down the stairs', 'self-care'),
('Stand up and move around', 'self-care'),
('Change into pajamas', 'self-care'),
('Set a bedtime', 'self-care'),
('Go to bed on time', 'self-care'),
('Get 8 hours sleep', 'self-care'),
('Wake up at your alarm', 'self-care'),
('Floss your teeth', 'self-care'),
('Use mouthwash', 'self-care'),
('Trim your nails', 'self-care'),
('File your nails', 'self-care'),
('Moisturize your hands', 'self-care'),
('Put on lip balm', 'self-care'),
('Wash your hair', 'self-care'),
('Condition your hair', 'self-care'),
('Dry your hair', 'self-care'),
('Shave if you want to', 'self-care'),
('Clip your toenails', 'self-care'),
('Change your bedsheets', 'self-care'),
('Wash your bedsheets', 'self-care'),
('Air out your bedroom', 'self-care'),
('Tidy your bedroom', 'self-care'),
('Put dirty clothes in the laundry basket', 'self-care'),
('Hang up your coat', 'self-care'),
('Put your shoes away', 'self-care'),
('Charge your phone', 'self-care'),
('Set an alarm for tomorrow', 'self-care'),
('Pack your bag for tomorrow', 'self-care'),
('Lay out clothes for tomorrow', 'self-care'),
('Check the weather for tomorrow', 'self-care'),
('Take a multivitamin', 'self-care'),
('Take vitamin D', 'self-care'),
('Sit in the sun for 10 minutes', 'self-care'),
('Wear sunscreen', 'self-care'),
('Wear a coat if it''s cold', 'self-care'),
('Wear a hat if it''s sunny', 'self-care'),
('Take an umbrella if it might rain', 'self-care'),
('Wear comfortable shoes', 'self-care'),
('Dress for the weather', 'self-care'),
('Check you have your keys', 'self-care'),
('Check you have your phone', 'self-care'),
('Check you have your wallet', 'self-care'),
('Charge your devices', 'self-care'),
('Clean your glasses', 'self-care'),
('Put in your contact lenses', 'self-care'),
('Take out your contact lenses', 'self-care'),
('Use eye drops if needed', 'self-care'),
('Rest your eyes from screens', 'self-care'),
('Blink regularly', 'self-care'),
('Adjust your posture', 'self-care'),
('Sit up straight', 'self-care'),
('Take a break from sitting', 'self-care'),
('Stretch your back', 'self-care'),
('Stretch your neck', 'self-care'),
('Roll your shoulders', 'self-care'),
('Shake out your hands', 'self-care'),
('Wiggle your toes', 'self-care'),
('Take 5 deep breaths', 'self-care'),
('Count to 10 slowly', 'self-care'),
('Drink some cold water', 'self-care'),
('Splash cold water on your face', 'self-care'),
('Step outside for a moment', 'self-care'),
('Listen to a song you like', 'self-care'),
('Watch a funny video', 'self-care'),
('Look at photos you like', 'self-care'),
('Pet an animal if you have one', 'self-care'),
('Water a plant', 'self-care'),
('Look out the window', 'self-care'),
('Notice 5 things you can see', 'self-care'),
('Notice 3 things you can hear', 'self-care'),
('Eat slowly and chew well', 'self-care'),
('Sit down to eat', 'self-care'),
('Use a plate for your food', 'self-care'),
('Drink from a glass not a bottle', 'self-care'),
('Have 3 meals today', 'self-care'),
('Don''t skip breakfast', 'self-care'),
('Have a proper lunch', 'self-care'),
('Eat dinner at a regular time', 'self-care'),
('Try to eat at the same times', 'self-care'),
('Keep snacks in the house', 'self-care'),
('Keep easy meals in the freezer', 'self-care'),
('Have breakfast cereal available', 'self-care'),
('Keep bread in the house', 'self-care'),
('Have milk in the fridge', 'self-care'),
('Keep tea bags in stock', 'self-care'),
('Have coffee if you drink it', 'self-care'),
('Keep sugar if you use it', 'self-care'),
('Stock up on toilet paper', 'self-care'),
('Have soap available', 'self-care'),
('Keep shampoo in stock', 'self-care'),
('Have toothpaste available', 'self-care'),
('Keep deodorant in stock', 'self-care'),
('Have clean towels', 'self-care'),
('Wash your towels', 'self-care'),
('Hang up wet towels', 'self-care'),
('Replace old towels', 'self-care'),
('Have a bath mat', 'self-care'),
('Keep the bathroom clean', 'self-care'),
('Wipe the bathroom sink', 'self-care'),
('Clean the toilet', 'self-care'),
('Empty the bathroom bin', 'self-care'),
('Refill the soap dispenser', 'self-care'),
('Replace the toilet roll', 'self-care'),
('Keep spare toilet rolls', 'self-care'),
('Have a shower curtain or door', 'self-care'),
('Keep the shower clean', 'self-care'),
('Prevent mold in the bathroom', 'self-care'),
('Open the bathroom window', 'self-care'),
('Use the bathroom fan', 'self-care'),
('Wipe up spills in the bathroom', 'self-care'),
('Keep bathroom products organized', 'self-care'),
('Throw out empty bottles', 'self-care'),
('Check expiry dates on products', 'self-care'),
('Replace old makeup', 'self-care'),
('Clean your makeup brushes', 'self-care'),
('Wash your face before bed', 'self-care'),
('Remove makeup before sleeping', 'self-care'),
('Use a clean pillowcase', 'self-care'),
('Wash your pillowcases weekly', 'self-care'),
('Have clean sheets on your bed', 'self-care'),
('Make your bed each morning', 'self-care'),
('Keep your bedroom tidy', 'self-care'),
('Don''t leave clothes on the floor', 'self-care'),
('Put dirty clothes in the wash', 'self-care'),
('Hang up clean clothes', 'self-care'),
('Fold clean clothes', 'self-care'),
('Put clean clothes away', 'self-care'),
('Sort clothes by type', 'self-care'),
('Keep underwear and socks together', 'self-care'),
('Have enough clean underwear', 'self-care'),
('Have enough clean socks', 'self-care'),
('Wear clean clothes each day', 'self-care'),
('Change your underwear daily', 'self-care'),
('Change your socks daily', 'self-care'),
('Wear clean pajamas', 'self-care'),
('Have clothes for different weather', 'self-care'),
('Have clothes for different occasions', 'self-care'),
('Keep one smart outfit', 'self-care'),
('Have comfortable clothes for home', 'self-care'),
('Wear clothes that fit', 'self-care'),
('Mend torn clothes', 'self-care'),
('Sew on loose buttons', 'self-care'),
('Replace worn out clothes', 'self-care'),
('Donate clothes you don''t wear', 'self-care'),
('Keep your wardrobe organized', 'self-care'),
('Know where your clothes are', 'self-care'),
('Have a coat for winter', 'self-care'),
('Have a waterproof jacket', 'self-care'),
('Have warm clothes for cold days', 'self-care'),
('Have light clothes for warm days', 'self-care'),
('Check the weather before dressing', 'self-care'),
('Dress appropriately for the day', 'self-care'),
('Wear layers you can remove', 'self-care'),
('Keep a spare outfit at home', 'self-care'),
('Have clean clothes ready', 'self-care'),
('Plan what to wear the night before', 'self-care'),
('Iron clothes if needed', 'self-care'),
('Hang clothes to prevent wrinkles', 'self-care'),
('Fold clothes neatly', 'self-care'),
('Store seasonal clothes away', 'self-care'),
('Rotate your wardrobe by season', 'self-care'),
('Keep shoes clean', 'self-care'),
('Polish shoes if needed', 'self-care'),
('Replace worn out shoes', 'self-care'),
('Have comfortable shoes for walking', 'self-care'),
('Have shoes for different weather', 'self-care'),
('Keep shoes by the door', 'self-care'),
('Have indoor slippers', 'self-care'),
('Wear appropriate footwear', 'self-care'),
('Take care of your feet', 'self-care'),
('Wear socks with closed shoes', 'self-care');

-- Insert practical financial tasks (200 items)
INSERT INTO small_wins (title, category) VALUES
('Check your bank balance', 'financial'),
('Look at your bank app', 'financial'),
('Check recent transactions', 'financial'),
('Review spending this week', 'financial'),
('Write down your income', 'financial'),
('List your regular expenses', 'financial'),
('Calculate monthly rent', 'financial'),
('Calculate monthly bills', 'financial'),
('Work out food budget', 'financial'),
('Plan your spending', 'financial'),
('Set a weekly budget', 'financial'),
('Track what you spend today', 'financial'),
('Keep receipts', 'financial'),
('Write down purchases', 'financial'),
('Check you can afford something', 'financial'),
('Wait before buying non-essentials', 'financial'),
('Make a shopping list', 'financial'),
('Stick to your shopping list', 'financial'),
('Compare prices', 'financial'),
('Look for deals', 'financial'),
('Use a loyalty card', 'financial'),
('Check for student discounts', 'financial'),
('Ask about discounts', 'financial'),
('Buy own-brand products', 'financial'),
('Shop at budget supermarkets', 'financial'),
('Buy reduced items', 'financial'),
('Check reduced section', 'financial'),
('Shop in the evening for reductions', 'financial'),
('Freeze food before it expires', 'financial'),
('Use up food before buying more', 'financial'),
('Plan meals around what you have', 'financial'),
('Cook at home', 'financial'),
('Make packed lunches', 'financial'),
('Avoid takeaways', 'financial'),
('Make coffee at home', 'financial'),
('Bring a water bottle', 'financial'),
('Avoid buying drinks out', 'financial'),
('Save £1 today', 'financial'),
('Put spare change aside', 'financial'),
('Transfer money to savings', 'financial'),
('Set up a savings account', 'financial'),
('Save a small amount regularly', 'financial'),
('Have an emergency fund', 'financial'),
('Keep some cash at home', 'financial'),
('Know where your money is', 'financial'),
('Check when rent is due', 'financial'),
('Pay rent on time', 'financial'),
('Set a rent reminder', 'financial'),
('Keep proof of rent payment', 'financial'),
('Know your tenancy dates', 'financial'),
('Read your tenancy agreement', 'financial'),
('Know your tenant rights', 'financial'),
('Know your landlord''s duties', 'financial'),
('Report repairs to landlord', 'financial'),
('Keep records of repair requests', 'financial'),
('Take photos of any damage', 'financial'),
('Document property condition', 'financial'),
('Keep your deposit safe', 'financial'),
('Know about deposit protection', 'financial'),
('Get deposit protection details', 'financial'),
('Check your council tax band', 'financial'),
('Know if you pay council tax', 'financial'),
('Apply for council tax reduction', 'financial'),
('Check single person discount', 'financial'),
('Apply for student exemption', 'financial'),
('Pay council tax on time', 'financial'),
('Set up council tax direct debit', 'financial'),
('Keep council tax letters', 'financial'),
('Know your council tax dates', 'financial'),
('Contact council if struggling', 'financial'),
('List all your bills', 'financial'),
('Know when bills are due', 'financial'),
('Set bill reminders', 'financial'),
('Pay bills on time', 'financial'),
('Set up direct debits', 'financial'),
('Check direct debits go out', 'financial'),
('Keep bills organized', 'financial'),
('File bills in one place', 'financial'),
('Keep energy bills', 'financial'),
('Keep water bills', 'financial'),
('Keep internet bills', 'financial'),
('Keep phone bills', 'financial'),
('Check your energy meter', 'financial'),
('Submit meter readings', 'financial'),
('Take meter reading photos', 'financial'),
('Check energy usage', 'financial'),
('Turn off lights to save money', 'financial'),
('Unplug devices to save money', 'financial'),
('Use less heating to save money', 'financial'),
('Compare energy suppliers', 'financial'),
('Switch energy supplier', 'financial'),
('Check you''re on best tariff', 'financial'),
('Apply for Warm Home Discount', 'financial'),
('Check water meter if you have one', 'financial'),
('Use less water to save money', 'financial'),
('Fix dripping taps', 'financial'),
('Report water leaks', 'financial'),
('Check if you need TV licence', 'financial'),
('Buy TV licence if needed', 'financial'),
('Check TV licence expiry', 'financial'),
('Renew TV licence on time', 'financial'),
('Check phone contract', 'financial'),
('Know when contract ends', 'financial'),
('Compare phone deals', 'financial'),
('Switch to cheaper phone plan', 'financial'),
('Use WiFi instead of data', 'financial'),
('Check internet contract', 'financial'),
('Compare broadband deals', 'financial'),
('Switch to cheaper broadband', 'financial'),
('Check broadband speed', 'financial'),
('Report broadband problems', 'financial'),
('Cancel unused subscriptions', 'financial'),
('List all subscriptions', 'financial'),
('Check subscription costs', 'financial'),
('Cancel free trials before charged', 'financial'),
('Set trial end reminders', 'financial'),
('Review streaming services', 'financial'),
('Share subscriptions with family', 'financial'),
('Use free alternatives', 'financial'),
('Check bank charges', 'financial'),
('Avoid overdraft fees', 'financial'),
('Stay within your overdraft', 'financial'),
('Check overdraft limit', 'financial'),
('Ask to reduce overdraft', 'financial'),
('Don''t use overdraft if possible', 'financial'),
('Check for unauthorized charges', 'financial'),
('Report wrong charges', 'financial'),
('Keep bank statements', 'financial'),
('Check statements monthly', 'financial'),
('Shred old statements', 'financial'),
('Keep important documents safe', 'financial'),
('Have a filing system', 'financial'),
('Keep tax documents', 'financial'),
('Keep payslips', 'financial'),
('Keep benefit letters', 'financial'),
('Keep medical letters', 'financial'),
('Organize paperwork', 'financial'),
('Deal with one letter today', 'financial'),
('Open all your mail', 'financial'),
('Don''t ignore letters', 'financial'),
('Reply to important letters', 'financial'),
('Keep copies of sent letters', 'financial'),
('Note down reference numbers', 'financial'),
('Keep appointment letters', 'financial'),
('Research Universal Credit', 'financial'),
('Check Universal Credit eligibility', 'financial'),
('Start Universal Credit application', 'financial'),
('Gather documents for UC', 'financial'),
('Keep UC appointment', 'financial'),
('Report changes to UC', 'financial'),
('Check UC payment date', 'financial'),
('Budget for monthly UC payment', 'financial'),
('Keep UC journal updated', 'financial'),
('Respond to UC messages', 'financial'),
('Check UC online account', 'financial'),
('Research PIP', 'financial'),
('Check PIP eligibility', 'financial'),
('Request PIP form', 'financial'),
('Fill in PIP form', 'financial'),
('Get help with PIP form', 'financial'),
('Keep PIP appointment', 'financial'),
('Prepare for PIP assessment', 'financial'),
('Keep symptom diary', 'financial'),
('Get medical evidence', 'financial'),
('Research other benefits', 'financial'),
('Check benefit entitlement', 'financial'),
('Use benefits calculator', 'financial'),
('Contact Citizens Advice', 'financial'),
('Book benefits advice appointment', 'financial'),
('Ask for help with forms', 'financial'),
('Get support with applications', 'financial'),
('Check application progress', 'financial'),
('Chase up applications', 'financial'),
('Keep benefit decision letters', 'financial'),
('Check benefit payments', 'financial'),
('Report benefit problems', 'financial'),
('Know your benefit rights', 'financial'),
('Challenge wrong decisions', 'financial'),
('Get advice on appeals', 'financial'),
('Meet benefit conditions', 'financial'),
('Report changes promptly', 'financial'),
('Keep benefit appointments', 'financial'),
('Respond to benefit letters', 'financial'),
('Don''t miss benefit deadlines', 'financial'),
('Check payment went in', 'financial'),
('Budget benefit money carefully', 'financial'),
('Make benefit money last', 'financial'),
('Plan for monthly payments', 'financial'),
('Save some benefit money', 'financial'),
('Pay priority bills first', 'financial'),
('Pay rent first', 'financial'),
('Pay council tax second', 'financial'),
('Pay energy bills third', 'financial'),
('Pay water bills fourth', 'financial'),
('Then pay other bills', 'financial'),
('Budget for food', 'financial'),
('Budget for travel', 'financial'),
('Budget for phone', 'financial'),
('Budget for emergencies', 'financial'),
('Have a spending plan', 'financial'),
('Stick to your plan', 'financial'),
('Adjust plan if needed', 'financial'),
('Review budget weekly', 'financial'),
('Check you''re on track', 'financial');

-- Household tasks (200 items) - continuing in next section due to length
INSERT INTO small_wins (title, category) VALUES
('Wash one dish', 'household'),
('Wash 5 dishes', 'household'),
('Clear the sink', 'household'),
('Wipe the kitchen counter', 'household'),
('Wipe the kitchen table', 'household'),
('Sweep the kitchen floor', 'household'),
('Mop the kitchen floor', 'household'),
('Take out the rubbish', 'household'),
('Empty the bin', 'household'),
('Put a new bin bag in', 'household'),
('Wipe up spills', 'household'),
('Clean the hob', 'household'),
('Wipe the microwave', 'household'),
('Clean inside the microwave', 'household'),
('Wipe the kettle', 'household'),
('Descale the kettle', 'household'),
('Wipe the toaster', 'household'),
('Empty toaster crumb tray', 'household'),
('Clean the fridge door', 'household'),
('Wipe one fridge shelf', 'household'),
('Throw out old food', 'household'),
('Check food expiry dates', 'household'),
('Organize the fridge', 'household'),
('Clean the freezer', 'household'),
('Defrost the freezer', 'household'),
('Organize the freezer', 'household'),
('Label frozen food', 'household'),
('Check what''s in the freezer', 'household'),
('Use up frozen food', 'household'),
('Clean one cupboard', 'household'),
('Organize food cupboards', 'household'),
('Check what food you have', 'household'),
('Throw out expired food', 'household'),
('Wipe cupboard shelves', 'household'),
('Organize under the sink', 'household'),
('Check cleaning supplies', 'household'),
('Buy more cleaning products', 'household'),
('Stock up on bin bags', 'household'),
('Have washing up liquid', 'household'),
('Have dish cloths', 'household'),
('Replace old sponges', 'household'),
('Wash dish cloths', 'household'),
('Clean the sink', 'household'),
('Unblock the sink', 'household'),
('Clean the drain', 'household'),
('Put one thing away', 'household'),
('Put 5 things away', 'household'),
('Tidy one surface', 'household'),
('Clear the coffee table', 'household'),
('Tidy the living room', 'household'),
('Plump the cushions', 'household'),
('Straighten the rug', 'household'),
('Organize the TV area', 'household'),
('Tidy cables and wires', 'household'),
('Dust one surface', 'household'),
('Dust the TV', 'household'),
('Dust shelves', 'household'),
('Wipe down surfaces', 'household'),
('Clean light switches', 'household'),
('Wipe door handles', 'household'),
('Clean the mirror', 'household'),
('Wipe the windows', 'household'),
('Clean window sills', 'household'),
('Vacuum one room', 'household'),
('Vacuum the living room', 'household'),
('Vacuum the bedroom', 'household'),
('Vacuum the hallway', 'household'),
('Vacuum under furniture', 'household'),
('Empty the vacuum', 'household'),
('Check vacuum is working', 'household'),
('Sweep the floor', 'household'),
('Mop the floor', 'household'),
('Clean one room', 'household'),
('Tidy one room', 'household'),
('Do a 5 minute tidy', 'household'),
('Do a 10 minute clean', 'household'),
('Set a timer and tidy', 'household'),
('Put laundry in machine', 'household'),
('Start the washing machine', 'household'),
('Hang up wet washing', 'household'),
('Bring in dry washing', 'household'),
('Fold dry washing', 'household'),
('Put clean washing away', 'household'),
('Sort washing by color', 'household'),
('Check pockets before washing', 'household'),
('Use the right detergent', 'household'),
('Don''t overload the machine', 'household'),
('Clean the washing machine', 'household'),
('Check washing machine filter', 'household'),
('Hang clothes to dry', 'household'),
('Use a clothes horse', 'household'),
('Hang washing outside if dry', 'household'),
('Bring washing in before rain', 'household'),
('Iron one item', 'household'),
('Iron work clothes', 'household'),
('Hang clothes neatly', 'household'),
('Fold clothes properly', 'household'),
('Match up socks', 'household'),
('Put socks in pairs', 'household'),
('Organize your drawers', 'household'),
('Tidy your wardrobe', 'household'),
('Hang up coats', 'household'),
('Put shoes away', 'household'),
('Keep hallway clear', 'household'),
('Don''t leave bags on floor', 'household'),
('Have a place for keys', 'household'),
('Keep keys in same place', 'household'),
('Have a place for post', 'household'),
('Sort post when it arrives', 'household'),
('Deal with junk mail', 'household'),
('Recycle paper', 'household'),
('Recycle cardboard', 'household'),
('Recycle plastic', 'household'),
('Recycle glass', 'household'),
('Recycle cans', 'household'),
('Know what can be recycled', 'household'),
('Rinse recycling', 'household'),
('Take recycling out', 'household'),
('Know bin collection days', 'household'),
('Put bins out on time', 'household'),
('Bring bins back in', 'household'),
('Keep bins clean', 'household'),
('Clean the toilet', 'household'),
('Scrub the toilet bowl', 'household'),
('Wipe the toilet seat', 'household'),
('Clean around the toilet', 'household'),
('Clean the bathroom sink', 'household'),
('Wipe the bathroom mirror', 'household'),
('Clean the bath', 'household'),
('Clean the shower', 'household'),
('Wipe shower doors', 'household'),
('Clean shower curtain', 'household'),
('Scrub bathroom tiles', 'household'),
('Clean bathroom floor', 'household'),
('Wipe bathroom surfaces', 'household'),
('Empty bathroom bin', 'household'),
('Replace toilet roll', 'household'),
('Stock spare toilet rolls', 'household'),
('Refill soap', 'household'),
('Refill hand wash', 'household'),
('Replace hand towel', 'household'),
('Wash bathroom towels', 'household'),
('Wash bath mat', 'household'),
('Hang up wet towels', 'household'),
('Don''t leave wet towels on floor', 'household'),
('Wipe up bathroom spills', 'household'),
('Prevent bathroom mold', 'household'),
('Open bathroom window', 'household'),
('Use bathroom extractor fan', 'household'),
('Keep bathroom ventilated', 'household'),
('Wipe condensation', 'household'),
('Check for leaks', 'household'),
('Fix dripping taps', 'household'),
('Report bathroom problems', 'household'),
('Unblock bathroom drain', 'household'),
('Clean drain cover', 'household'),
('Remove hair from drain', 'household'),
('Keep plunger handy', 'household'),
('Know how to use plunger', 'household'),
('Have basic cleaning supplies', 'household'),
('Have toilet cleaner', 'household'),
('Have bathroom cleaner', 'household'),
('Have bleach', 'household'),
('Have rubber gloves', 'household'),
('Use cleaning products safely', 'household'),
('Read cleaning product labels', 'household'),
('Store cleaning products safely', 'household'),
('Keep cleaning products away from food', 'household'),
('Ventilate when cleaning', 'household'),
('Change a lightbulb', 'household'),
('Know where fuse box is', 'household'),
('Know how to reset fuses', 'household'),
('Check smoke alarm works', 'household'),
('Test smoke alarm monthly', 'household'),
('Change smoke alarm battery', 'household'),
('Have working smoke alarm', 'household'),
('Know fire escape route', 'household'),
('Keep fire exits clear', 'household'),
('Don''t block exits', 'household'),
('Have emergency numbers', 'household'),
('Know landlord''s number', 'household'),
('Know how to report repairs', 'household'),
('Report urgent repairs quickly', 'household'),
('Take photos of problems', 'household'),
('Keep repair records', 'household'),
('Follow up on repairs', 'household'),
('Check repairs are done properly', 'household'),
('Know what landlord must fix', 'household'),
('Know what you must fix', 'household'),
('Do small repairs yourself', 'household'),
('Tighten loose screws', 'household'),
('Oil squeaky hinges', 'household'),
('Fix stuck drawers', 'household'),
('Adjust cabinet doors', 'household'),
('Keep basic tools', 'household'),
('Have a screwdriver', 'household'),
('Have a hammer', 'household'),
('Have pliers', 'household'),
('Have tape', 'household'),
('Have spare batteries', 'household');

-- Social tasks (200 items)
INSERT INTO small_wins (title, category) VALUES
('Reply to a text message', 'social'),
('Send a text to someone', 'social'),
('Answer the phone', 'social'),
('Make a phone call', 'social'),
('Call a family member', 'social'),
('Text a friend', 'social'),
('Check your messages', 'social'),
('Respond to messages', 'social'),
('Return a missed call', 'social'),
('Listen to voicemail', 'social'),
('Delete old messages', 'social'),
('Keep phone charged', 'social'),
('Have phone credit', 'social'),
('Top up phone if needed', 'social'),
('Check you can make calls', 'social'),
('Check you can receive calls', 'social'),
('Save important numbers', 'social'),
('Have emergency numbers saved', 'social'),
('Know who to call for help', 'social'),
('Have GP number saved', 'social'),
('Have dentist number saved', 'social'),
('Have landlord number saved', 'social'),
('Have family numbers saved', 'social'),
('Have friend numbers saved', 'social'),
('Say hello to someone', 'social'),
('Say good morning', 'social'),
('Say good afternoon', 'social'),
('Say good evening', 'social'),
('Say please', 'social'),
('Say thank you', 'social'),
('Say excuse me', 'social'),
('Say sorry if needed', 'social'),
('Hold the door for someone', 'social'),
('Let someone pass', 'social'),
('Smile at someone', 'social'),
('Wave to a neighbor', 'social'),
('Nod to acknowledge someone', 'social'),
('Make eye contact', 'social'),
('Listen when someone talks', 'social'),
('Pay attention in conversation', 'social'),
('Ask how someone is', 'social'),
('Answer when asked how you are', 'social'),
('Have a short conversation', 'social'),
('Chat with a shop assistant', 'social'),
('Be polite to staff', 'social'),
('Thank shop workers', 'social'),
('Be patient in queues', 'social'),
('Wait your turn', 'social'),
('Don''t push in queues', 'social'),
('Respect personal space', 'social'),
('Stand at appropriate distance', 'social'),
('Don''t stand too close', 'social'),
('Respect others'' privacy', 'social'),
('Keep noise down', 'social'),
('Be quiet in the evening', 'social'),
('Don''t play loud music late', 'social'),
('Use headphones', 'social'),
('Be considerate of neighbors', 'social'),
('Don''t slam doors', 'social'),
('Close doors quietly', 'social'),
('Walk quietly in shared spaces', 'social'),
('Keep shared areas tidy', 'social'),
('Clean up after yourself', 'social'),
('Don''t leave mess in shared spaces', 'social'),
('Take turns with shared facilities', 'social'),
('Share washing machine time', 'social'),
('Don''t hog shared spaces', 'social'),
('Be fair with shared resources', 'social'),
('Communicate with housemates', 'social'),
('Tell housemates if there''s a problem', 'social'),
('Discuss issues calmly', 'social'),
('Listen to housemates'' concerns', 'social'),
('Compromise when needed', 'social'),
('Respect housemates'' belongings', 'social'),
('Don''t use others'' things without asking', 'social'),
('Ask before borrowing', 'social'),
('Return borrowed items', 'social'),
('Replace things you use up', 'social'),
('Buy shared supplies', 'social'),
('Take turns buying toilet paper', 'social'),
('Share cost of cleaning products', 'social'),
('Pay your share of bills', 'social'),
('Pay housemates back promptly', 'social'),
('Don''t owe people money', 'social'),
('Keep track of shared expenses', 'social'),
('Settle up regularly', 'social'),
('Be honest about money', 'social'),
('Discuss bills openly', 'social'),
('Agree on bill splitting', 'social'),
('Pay bills on time', 'social'),
('Don''t leave others to pay', 'social'),
('Be reliable', 'social'),
('Do what you say you''ll do', 'social'),
('Keep promises', 'social'),
('Be on time', 'social'),
('Let people know if you''re late', 'social'),
('Cancel plans properly', 'social'),
('Give notice if you can''t make it', 'social'),
('Don''t cancel last minute', 'social'),
('Respect people''s time', 'social'),
('Turn up to appointments', 'social'),
('Arrive on time for appointments', 'social'),
('Bring required documents', 'social'),
('Be prepared for meetings', 'social'),
('Know what to bring', 'social'),
('Check appointment details', 'social'),
('Know where to go', 'social'),
('Know what time to arrive', 'social'),
('Plan journey in advance', 'social'),
('Leave enough time to get there', 'social'),
('Check bus times', 'social'),
('Check train times', 'social'),
('Have travel money ready', 'social'),
('Know how to get there', 'social'),
('Look up directions', 'social'),
('Use maps on phone', 'social'),
('Ask for directions if lost', 'social'),
('Allow extra time', 'social'),
('Don''t rush', 'social'),
('Stay calm when traveling', 'social'),
('Have phone charged for journey', 'social'),
('Bring headphones for journey', 'social'),
('Bring water for journey', 'social'),
('Bring snack for journey', 'social'),
('Dress appropriately', 'social'),
('Wear clean clothes out', 'social'),
('Look presentable', 'social'),
('Dress for the occasion', 'social'),
('Wear weather-appropriate clothes', 'social'),
('Bring a coat if needed', 'social'),
('Bring an umbrella if raining', 'social'),
('Check weather before going out', 'social'),
('Plan what to wear', 'social'),
('Have clean clothes ready', 'social'),
('Prepare the night before', 'social'),
('Pack bag the night before', 'social'),
('Know what you need to bring', 'social'),
('Make a list of what to bring', 'social'),
('Check you have everything', 'social'),
('Have keys before leaving', 'social'),
('Have phone before leaving', 'social'),
('Have wallet before leaving', 'social'),
('Have necessary documents', 'social'),
('Bring ID if needed', 'social'),
('Bring appointment letter', 'social'),
('Bring any forms needed', 'social'),
('Bring pen and paper', 'social'),
('Be prepared to take notes', 'social'),
('Write down important information', 'social'),
('Ask for information in writing', 'social'),
('Get receipts', 'social'),
('Keep appointment cards', 'social'),
('Note down next appointment', 'social'),
('Put appointments in phone', 'social'),
('Set appointment reminders', 'social'),
('Check calendar daily', 'social'),
('Know what''s coming up', 'social'),
('Plan your week', 'social'),
('Know what you''re doing tomorrow', 'social'),
('Have a routine', 'social'),
('Stick to regular times', 'social'),
('Go to bed at same time', 'social'),
('Wake up at same time', 'social'),
('Eat at regular times', 'social'),
('Have a daily structure', 'social'),
('Plan your day', 'social'),
('Know what needs doing', 'social'),
('Prioritize important tasks', 'social'),
('Do urgent things first', 'social'),
('Don''t put things off', 'social'),
('Deal with things promptly', 'social'),
('Respond to letters quickly', 'social'),
('Reply to messages same day', 'social'),
('Return calls promptly', 'social'),
('Don''t ignore communications', 'social'),
('Keep people informed', 'social'),
('Let people know your plans', 'social'),
('Tell people if plans change', 'social'),
('Communicate clearly', 'social'),
('Speak clearly', 'social'),
('Don''t mumble', 'social'),
('Make yourself understood', 'social'),
('Ask if you don''t understand', 'social'),
('Ask people to repeat if needed', 'social'),
('Clarify if unsure', 'social'),
('Check you understood correctly', 'social'),
('Confirm details', 'social'),
('Repeat back important information', 'social'),
('Write down key points', 'social'),
('Take notes in meetings', 'social'),
('Keep records of conversations', 'social'),
('Note down what was agreed', 'social'),
('Follow up on agreements', 'social'),
('Do what was agreed', 'social'),
('Check in with people', 'social'),
('Update people on progress', 'social'),
('Let people know outcomes', 'social'),
('Thank people for their help', 'social'),
('Acknowledge support', 'social'),
('Show appreciation', 'social'),
('Be grateful', 'social'),
('Recognize kindness', 'social');

-- Learning tasks (100 items)
INSERT INTO small_wins (title, category) VALUES
('Read about budgeting', 'learning'),
('Watch a budgeting video', 'learning'),
('Learn about Universal Credit', 'learning'),
('Research council tax', 'learning'),
('Read about tenant rights', 'learning'),
('Learn about bills', 'learning'),
('Understand energy bills', 'learning'),
('Learn about water bills', 'learning'),
('Research TV licence', 'learning'),
('Learn about phone contracts', 'learning'),
('Understand broadband contracts', 'learning'),
('Read about deposits', 'learning'),
('Learn about tenancy agreements', 'learning'),
('Research renting rights', 'learning'),
('Learn about repairs', 'learning'),
('Understand landlord duties', 'learning'),
('Learn about PIP', 'learning'),
('Research benefits', 'learning'),
('Learn about housing benefit', 'learning'),
('Understand benefit claims', 'learning'),
('Learn about Citizens Advice', 'learning'),
('Find local support services', 'learning'),
('Research food banks', 'learning'),
('Learn about debt advice', 'learning'),
('Understand credit scores', 'learning'),
('Learn about bank accounts', 'learning'),
('Research savings accounts', 'learning'),
('Learn about direct debits', 'learning'),
('Understand standing orders', 'learning'),
('Learn about overdrafts', 'learning'),
('Research student finance', 'learning'),
('Learn about council services', 'learning'),
('Understand recycling rules', 'learning'),
('Learn about bin collections', 'learning'),
('Research local services', 'learning'),
('Learn about GP registration', 'learning'),
('Understand NHS services', 'learning'),
('Learn about prescriptions', 'learning'),
('Research dental care', 'learning'),
('Learn about opticians', 'learning'),
('Understand mental health services', 'learning'),
('Learn about crisis support', 'learning'),
('Research emergency services', 'learning'),
('Learn when to call 999', 'learning'),
('Understand when to call 111', 'learning'),
('Learn about A&E', 'learning'),
('Research urgent care', 'learning'),
('Learn about pharmacies', 'learning'),
('Understand medication', 'learning'),
('Learn about healthy eating', 'learning'),
('Research nutrition', 'learning'),
('Learn about food safety', 'learning'),
('Understand food storage', 'learning'),
('Learn about food hygiene', 'learning'),
('Research meal planning', 'learning'),
('Learn basic cooking', 'learning'),
('Watch a cooking video', 'learning'),
('Learn a simple recipe', 'learning'),
('Research budget meals', 'learning'),
('Learn about food shopping', 'learning'),
('Understand food labels', 'learning'),
('Learn about expiry dates', 'learning'),
('Research food waste', 'learning'),
('Learn about freezing food', 'learning'),
('Understand defrosting', 'learning'),
('Learn about kitchen safety', 'learning'),
('Research fire safety', 'learning'),
('Learn about smoke alarms', 'learning'),
('Understand carbon monoxide', 'learning'),
('Learn about home safety', 'learning'),
('Research security', 'learning'),
('Learn about locks', 'learning'),
('Understand home insurance', 'learning'),
('Learn about contents insurance', 'learning'),
('Research cleaning methods', 'learning'),
('Learn about cleaning products', 'learning'),
('Understand laundry symbols', 'learning'),
('Learn how to wash clothes', 'learning'),
('Research stain removal', 'learning'),
('Learn about fabric care', 'learning'),
('Understand washing machine settings', 'learning'),
('Learn about drying clothes', 'learning'),
('Research ironing', 'learning'),
('Learn basic sewing', 'learning'),
('Understand clothing care', 'learning'),
('Learn about shoe care', 'learning'),
('Research wardrobe organization', 'learning'),
('Learn about sleep hygiene', 'learning'),
('Understand sleep importance', 'learning'),
('Learn about exercise', 'learning'),
('Research physical activity', 'learning'),
('Learn about mental health', 'learning'),
('Understand stress management', 'learning'),
('Learn about anxiety', 'learning'),
('Research depression', 'learning'),
('Learn about ADHD', 'learning'),
('Understand autism', 'learning'),
('Learn about neurodiversity', 'learning'),
('Research coping strategies', 'learning'),
('Learn about self-care', 'learning'),
('Understand boundaries', 'learning'),
('Learn about communication', 'learning'),
('Research social skills', 'learning');

-- Health tasks (100 items)
INSERT INTO small_wins (title, category) VALUES
('Take your medication', 'health'),
('Take morning medication', 'health'),
('Take evening medication', 'health'),
('Set medication reminder', 'health'),
('Refill prescription', 'health'),
('Order repeat prescription', 'health'),
('Collect prescription', 'health'),
('Check medication supply', 'health'),
('Store medication properly', 'health'),
('Keep medication in date', 'health'),
('Read medication instructions', 'health'),
('Take medication with food if needed', 'health'),
('Don''t skip medication', 'health'),
('Take full course of antibiotics', 'health'),
('Note medication side effects', 'health'),
('Report medication problems', 'health'),
('Book GP appointment', 'health'),
('Call GP surgery', 'health'),
('Register with a GP', 'health'),
('Find local GP', 'health'),
('Attend GP appointment', 'health'),
('Prepare for GP appointment', 'health'),
('Write down symptoms', 'health'),
('List questions for GP', 'health'),
('Bring medication list to appointment', 'health'),
('Tell GP about all symptoms', 'health'),
('Be honest with GP', 'health'),
('Ask GP questions', 'health'),
('Understand GP advice', 'health'),
('Follow GP instructions', 'health'),
('Book follow-up appointment', 'health'),
('Book dentist appointment', 'health'),
('Find a dentist', 'health'),
('Register with dentist', 'health'),
('Attend dentist appointment', 'health'),
('Brush teeth twice daily', 'health'),
('Brush teeth for 2 minutes', 'health'),
('Floss daily', 'health'),
('Use mouthwash', 'health'),
('Replace toothbrush regularly', 'health'),
('Book optician appointment', 'health'),
('Get eye test', 'health'),
('Wear glasses if prescribed', 'health'),
('Clean glasses daily', 'health'),
('Care for contact lenses', 'health'),
('Replace contact lenses on time', 'health'),
('Rest eyes from screens', 'health'),
('Follow 20-20-20 rule for eyes', 'health'),
('Drink water regularly', 'health'),
('Drink 6-8 glasses of water daily', 'health'),
('Carry water bottle', 'health'),
('Eat breakfast', 'health'),
('Eat regular meals', 'health'),
('Don''t skip meals', 'health'),
('Eat fruit daily', 'health'),
('Eat vegetables daily', 'health'),
('Eat balanced meals', 'health'),
('Include protein in meals', 'health'),
('Eat whole grains', 'health'),
('Limit sugary foods', 'health'),
('Limit processed foods', 'health'),
('Reduce salt intake', 'health'),
('Eat appropriate portions', 'health'),
('Don''t overeat', 'health'),
('Stop eating when full', 'health'),
('Eat slowly', 'health'),
('Chew food properly', 'health'),
('Sit down to eat', 'health'),
('Don''t eat in front of TV', 'health'),
('Plan meals', 'health'),
('Cook healthy meals', 'health'),
('Prepare vegetables', 'health'),
('Try new healthy foods', 'health'),
('Go for a walk', 'health'),
('Walk for 10 minutes', 'health'),
('Walk for 30 minutes', 'health'),
('Take the stairs', 'health'),
('Stand up regularly', 'health'),
('Stretch daily', 'health'),
('Do gentle exercise', 'health'),
('Move every hour', 'health'),
('Exercise at your own pace', 'health'),
('Don''t overdo exercise', 'health'),
('Rest when needed', 'health'),
('Get enough sleep', 'health'),
('Sleep 7-9 hours', 'health'),
('Go to bed at regular time', 'health'),
('Wake at regular time', 'health'),
('Avoid screens before bed', 'health'),
('Keep bedroom dark', 'health'),
('Keep bedroom cool', 'health'),
('Keep bedroom quiet', 'health'),
('Have comfortable bed', 'health'),
('Use comfortable pillow', 'health'),
('Wear comfortable pajamas', 'health'),
('Avoid caffeine after 2pm', 'health'),
('Limit alcohol', 'health'),
('Don''t smoke', 'health'),
('Seek smoking cessation help', 'health'),
('Avoid recreational drugs', 'health'),
('Seek addiction support if needed', 'health');

-- Grant permissions (already set in previous migration, but ensuring they're still in place)
GRANT SELECT ON small_wins TO anon, authenticated;
GRANT SELECT, INSERT ON user_small_wins_history TO anon, authenticated;
GRANT EXECUTE ON FUNCTION get_daily_small_wins TO anon, authenticated;
GRANT EXECUTE ON FUNCTION record_shown_wins TO anon, authenticated;
