/*
# Small Wins System

## Overview
Creates a database of 1000 small wins/tasks for the "Today's small wins" section.
Implements a 24-hour rotation system that shows different wins each day.

## Tables

### small_wins
Stores the database of 1000 small win suggestions.
- `id` (bigserial, primary key) - Unique identifier
- `title` (text, not null) - The small win text/task description
- `category` (text, not null) - Category: 'self-care', 'financial', 'household', 'social', 'learning', 'health'
- `created_at` (timestamptz, default: now()) - Creation timestamp

### user_small_wins_history
Tracks which small wins have been shown to users and when.
- `id` (uuid, primary key) - Unique identifier
- `user_uuid` (text, not null) - User identifier (from localStorage for anonymous users)
- `small_win_id` (bigint, foreign key) - Reference to small_wins table
- `shown_at` (timestamptz, not null) - When this win was shown
- `created_at` (timestamptz, default: now()) - Creation timestamp

## RPC Functions

### get_daily_small_wins(p_user_uuid text, p_count int)
Returns a set of small wins for the user for today.
- Uses deterministic selection based on current date
- Avoids recently shown wins (within last 30 days)
- Returns specified count of wins (default 3)

## Security
- Public read access on small_wins table (no RLS needed - public data)
- Public insert/read access on user_small_wins_history (anonymous tracking)

## Data
Inserts 1000 diverse small wins across 6 categories:
- Self-care (200 items)
- Financial (200 items)
- Household (200 items)
- Social (200 items)
- Learning (100 items)
- Health (100 items)
*/

-- Create small_wins table
CREATE TABLE IF NOT EXISTS small_wins (
  id bigserial PRIMARY KEY,
  title text NOT NULL,
  category text NOT NULL CHECK (category IN ('self-care', 'financial', 'household', 'social', 'learning', 'health')),
  created_at timestamptz DEFAULT now()
);

-- Create user_small_wins_history table
CREATE TABLE IF NOT EXISTS user_small_wins_history (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_uuid text NOT NULL,
  small_win_id bigint NOT NULL REFERENCES small_wins(id) ON DELETE CASCADE,
  shown_at timestamptz NOT NULL,
  created_at timestamptz DEFAULT now()
);

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_user_small_wins_history_user_uuid ON user_small_wins_history(user_uuid);
CREATE INDEX IF NOT EXISTS idx_user_small_wins_history_shown_at ON user_small_wins_history(shown_at);

-- Insert 1000 small wins

-- Self-care wins (200 items)
INSERT INTO small_wins (title, category) VALUES
('Drink a glass of water', 'self-care'),
('Take 5 deep breaths', 'self-care'),
('Brush your teeth', 'self-care'),
('Wash your face', 'self-care'),
('Put on clean clothes', 'self-care'),
('Open a window for fresh air', 'self-care'),
('Stretch for 2 minutes', 'self-care'),
('Take your medication', 'self-care'),
('Eat one piece of fruit', 'self-care'),
('Make your bed', 'self-care'),
('Take a 5-minute walk', 'self-care'),
('Listen to one song you love', 'self-care'),
('Write down one thing you''re grateful for', 'self-care'),
('Shower or wash up', 'self-care'),
('Change your bedsheets', 'self-care'),
('Moisturize your skin', 'self-care'),
('Trim your nails', 'self-care'),
('Comb or brush your hair', 'self-care'),
('Put on deodorant', 'self-care'),
('Floss your teeth', 'self-care'),
('Take a multivitamin', 'self-care'),
('Do a 5-minute meditation', 'self-care'),
('Watch a funny video', 'self-care'),
('Pet an animal', 'self-care'),
('Look at photos that make you smile', 'self-care'),
('Sit in the sun for 5 minutes', 'self-care'),
('Take a relaxing bath', 'self-care'),
('Use a face mask', 'self-care'),
('Paint your nails', 'self-care'),
('Try a new hairstyle', 'self-care'),
('Wear something that makes you feel good', 'self-care'),
('Light a scented candle', 'self-care'),
('Water a plant', 'self-care'),
('Tidy one small area', 'self-care'),
('Make a cup of tea or coffee', 'self-care'),
('Eat breakfast', 'self-care'),
('Pack a healthy snack', 'self-care'),
('Set a bedtime alarm', 'self-care'),
('Turn off screens 30 minutes before bed', 'self-care'),
('Write in a journal for 5 minutes', 'self-care'),
('Do a puzzle or brain game', 'self-care'),
('Read one page of a book', 'self-care'),
('Doodle or color for fun', 'self-care'),
('Dance to one song', 'self-care'),
('Sing along to music', 'self-care'),
('Watch the sunrise or sunset', 'self-care'),
('Stargaze for 5 minutes', 'self-care'),
('Take a photo of something beautiful', 'self-care'),
('Compliment yourself in the mirror', 'self-care'),
('Say "no" to something you don''t want to do', 'self-care'),
('Ask for help with something', 'self-care'),
('Tell someone you''re struggling', 'self-care'),
('Book a doctor''s appointment', 'self-care'),
('Book a dentist appointment', 'self-care'),
('Book a therapy session', 'self-care'),
('Take a mental health day', 'self-care'),
('Unfollow accounts that make you feel bad', 'self-care'),
('Delete one app that wastes your time', 'self-care'),
('Set a boundary with someone', 'self-care'),
('Forgive yourself for one mistake', 'self-care'),
('Let go of one thing you can''t control', 'self-care'),
('Accept one compliment gracefully', 'self-care'),
('Wear sunscreen', 'self-care'),
('Take off makeup before bed', 'self-care'),
('Exfoliate your skin', 'self-care'),
('Deep condition your hair', 'self-care'),
('Trim split ends', 'self-care'),
('Shave or groom as desired', 'self-care'),
('Apply lip balm', 'self-care'),
('Use hand cream', 'self-care'),
('Massage your feet', 'self-care'),
('Massage your shoulders', 'self-care'),
('Do neck stretches', 'self-care'),
('Roll your ankles', 'self-care'),
('Wiggle your toes', 'self-care'),
('Shake out your hands', 'self-care'),
('Blink and rest your eyes', 'self-care'),
('Look away from screens for 5 minutes', 'self-care'),
('Adjust your posture', 'self-care'),
('Stand up and move around', 'self-care'),
('Drink herbal tea', 'self-care'),
('Eat a vegetable', 'self-care'),
('Have a healthy breakfast', 'self-care'),
('Pack lunch instead of buying', 'self-care'),
('Meal prep one thing', 'self-care'),
('Try a new healthy recipe', 'self-care'),
('Cut up fruit for snacks', 'self-care'),
('Make a smoothie', 'self-care'),
('Drink less caffeine today', 'self-care'),
('Avoid alcohol today', 'self-care'),
('Go to bed 30 minutes earlier', 'self-care'),
('Wake up without hitting snooze', 'self-care'),
('Take a power nap (20 minutes)', 'self-care'),
('Use a sleep mask', 'self-care'),
('Try earplugs for better sleep', 'self-care'),
('Keep your bedroom cool', 'self-care'),
('Avoid screens in the bedroom', 'self-care'),
('Read before bed instead of scrolling', 'self-care'),
('Practice progressive muscle relaxation', 'self-care'),
('Try the 4-7-8 breathing technique', 'self-care'),
('Do a body scan meditation', 'self-care'),
('Listen to calming music', 'self-care'),
('Listen to nature sounds', 'self-care'),
('Try a guided meditation app', 'self-care'),
('Practice mindful eating', 'self-care'),
('Eat without distractions', 'self-care'),
('Chew your food slowly', 'self-care'),
('Notice 5 things you can see', 'self-care'),
('Notice 4 things you can touch', 'self-care'),
('Notice 3 things you can hear', 'self-care'),
('Notice 2 things you can smell', 'self-care'),
('Notice 1 thing you can taste', 'self-care'),
('Ground yourself with the 5-4-3-2-1 technique', 'self-care'),
('Hold an ice cube to calm anxiety', 'self-care'),
('Splash cold water on your face', 'self-care'),
('Hug yourself', 'self-care'),
('Place your hand on your heart', 'self-care'),
('Say a positive affirmation', 'self-care'),
('Challenge one negative thought', 'self-care'),
('Reframe one worry', 'self-care'),
('Write down your feelings', 'self-care'),
('Cry if you need to', 'self-care'),
('Laugh at something silly', 'self-care'),
('Allow yourself to feel your emotions', 'self-care'),
('Validate your own feelings', 'self-care'),
('Be kind to yourself today', 'self-care'),
('Treat yourself like you''d treat a friend', 'self-care'),
('Give yourself permission to rest', 'self-care'),
('Celebrate one small achievement', 'self-care'),
('Acknowledge your progress', 'self-care'),
('Recognize your strengths', 'self-care'),
('Appreciate your body', 'self-care'),
('Thank yourself for trying', 'self-care'),
('Wear comfortable clothes', 'self-care'),
('Take off restrictive clothing', 'self-care'),
('Wear your favorite outfit', 'self-care'),
('Try a new style', 'self-care'),
('Organize your wardrobe', 'self-care'),
('Donate clothes you don''t wear', 'self-care'),
('Mend one piece of clothing', 'self-care'),
('Polish your shoes', 'self-care'),
('Clean your glasses', 'self-care'),
('Replace worn-out underwear', 'self-care'),
('Buy new socks', 'self-care'),
('Get a haircut', 'self-care'),
('Try a new hair product', 'self-care'),
('Experiment with makeup', 'self-care'),
('Go makeup-free today', 'self-care'),
('Wear jewelry you love', 'self-care'),
('Spray on perfume or cologne', 'self-care'),
('Dress up for no reason', 'self-care'),
('Take a selfie you like', 'self-care'),
('Delete unflattering photos', 'self-care'),
('Update your profile picture', 'self-care'),
('Curate your social media feed', 'self-care'),
('Take a break from social media', 'self-care'),
('Mute negative people online', 'self-care'),
('Join a supportive online community', 'self-care'),
('Share your story anonymously', 'self-care'),
('Read others'' recovery stories', 'self-care'),
('Watch a motivational video', 'self-care'),
('Listen to a helpful podcast', 'self-care'),
('Learn about your condition', 'self-care'),
('Research coping strategies', 'self-care'),
('Try one new coping skill', 'self-care'),
('Practice your favorite coping skill', 'self-care'),
('Update your safety plan', 'self-care'),
('Save crisis helpline numbers', 'self-care'),
('Identify your triggers', 'self-care'),
('Plan for a difficult situation', 'self-care'),
('Prepare for a stressful event', 'self-care'),
('Cancel plans if you need to', 'self-care'),
('Reschedule something overwhelming', 'self-care'),
('Break a big task into tiny steps', 'self-care'),
('Do just the first step of something', 'self-care'),
('Set a timer for 5 minutes and try', 'self-care'),
('Give yourself permission to stop', 'self-care'),
('Take a break when you need it', 'self-care'),
('Rest without guilt', 'self-care'),
('Do nothing for 10 minutes', 'self-care'),
('Sit quietly and breathe', 'self-care'),
('Enjoy a moment of peace', 'self-care'),
('Appreciate the present moment', 'self-care'),
('Notice something beautiful', 'self-care'),
('Find one thing to smile about', 'self-care'),
('Remember you''re doing your best', 'self-care'),
('Know that tomorrow is a new day', 'self-care'),
('Believe that things can get better', 'self-care'),
('Hold onto hope', 'self-care'),
('Reach out to a helpline if needed', 'self-care'),
('Text a crisis line', 'self-care'),
('Call a friend in crisis', 'self-care'),
('Go to A&E if you''re in danger', 'self-care'),
('Keep yourself safe today', 'self-care'),
('Survive today - that''s enough', 'self-care');

-- Financial wins (200 items)
INSERT INTO small_wins (title, category) VALUES
('Check your bank balance', 'financial'),
('Look at your recent transactions', 'financial'),
('Review your spending this week', 'financial'),
('Set up a budget spreadsheet', 'financial'),
('Download a budgeting app', 'financial'),
('Calculate your monthly income', 'financial'),
('List your monthly expenses', 'financial'),
('Identify one unnecessary expense', 'financial'),
('Cancel one unused subscription', 'financial'),
('Unsubscribe from marketing emails', 'financial'),
('Save £1 today', 'financial'),
('Put spare change in a jar', 'financial'),
('Transfer £5 to savings', 'financial'),
('Set up automatic savings', 'financial'),
('Open a savings account', 'financial'),
('Research high-interest savings accounts', 'financial'),
('Check your credit score', 'financial'),
('Sign up for credit monitoring', 'financial'),
('Review your credit report', 'financial'),
('Dispute an error on your credit report', 'financial'),
('Pay one bill on time', 'financial'),
('Set up a bill payment reminder', 'financial'),
('Automate one bill payment', 'financial'),
('Make a list of all your bills', 'financial'),
('Note down all bill due dates', 'financial'),
('Check when your rent is due', 'financial'),
('Set a rent payment reminder', 'financial'),
('Review your tenancy agreement', 'financial'),
('Check your council tax band', 'financial'),
('Apply for council tax reduction', 'financial'),
('Check if you qualify for single person discount', 'financial'),
('Apply for student council tax exemption', 'financial'),
('Research Universal Credit', 'financial'),
('Check Universal Credit eligibility', 'financial'),
('Start a Universal Credit application', 'financial'),
('Gather documents for benefits claim', 'financial'),
('Book a benefits advice appointment', 'financial'),
('Call Citizens Advice', 'financial'),
('Research PIP eligibility', 'financial'),
('Request a PIP claim form', 'financial'),
('Fill out one section of benefits form', 'financial'),
('Ask for help with benefits application', 'financial'),
('Keep a symptom diary for PIP', 'financial'),
('Gather medical evidence', 'financial'),
('Request a fit note from GP', 'financial'),
('Apply for Housing Benefit', 'financial'),
('Check if you''re paying too much rent', 'financial'),
('Research cheaper accommodation', 'financial'),
('Look at house shares', 'financial'),
('Calculate bills per person in house share', 'financial'),
('Compare energy suppliers', 'financial'),
('Switch to a cheaper energy tariff', 'financial'),
('Submit meter readings', 'financial'),
('Check if you''re on the best energy deal', 'financial'),
('Apply for Warm Home Discount', 'financial'),
('Research water bill discounts', 'financial'),
('Check if you need a TV licence', 'financial'),
('Apply for TV licence discount', 'financial'),
('Compare broadband providers', 'financial'),
('Negotiate a better broadband deal', 'financial'),
('Check your phone contract', 'financial'),
('Switch to a SIM-only deal', 'financial'),
('Compare mobile phone plans', 'financial'),
('Cancel unused phone insurance', 'financial'),
('Review all insurance policies', 'financial'),
('Shop around for cheaper insurance', 'financial'),
('Check if you need contents insurance', 'financial'),
('Make a list of valuable possessions', 'financial'),
('Take photos of valuables for insurance', 'financial'),
('Store receipts for expensive items', 'financial'),
('Register products for warranty', 'financial'),
('Check warranty expiry dates', 'financial'),
('Use a warranty before it expires', 'financial'),
('Return a faulty item', 'financial'),
('Request a refund for poor service', 'financial'),
('Complain about unfair charges', 'financial'),
('Dispute a bank charge', 'financial'),
('Request a chargeback', 'financial'),
('Report fraud to your bank', 'financial'),
('Freeze your credit if needed', 'financial'),
('Change passwords after a breach', 'financial'),
('Enable two-factor authentication', 'financial'),
('Review bank security settings', 'financial'),
('Set up spending alerts', 'financial'),
('Check for unusual transactions', 'financial'),
('Report a lost or stolen card', 'financial'),
('Order a replacement card', 'financial'),
('Update card details on subscriptions', 'financial'),
('Remove saved card details from websites', 'financial'),
('Clear saved payment methods', 'financial'),
('Use a password manager', 'financial'),
('Create a strong password', 'financial'),
('Never share your PIN', 'financial'),
('Shred financial documents', 'financial'),
('File important documents', 'financial'),
('Organize receipts', 'financial'),
('Keep a spending diary for one day', 'financial'),
('Track every purchase today', 'financial'),
('Use cash instead of card today', 'financial'),
('Try the envelope budgeting method', 'financial'),
('Allocate money to different categories', 'financial'),
('Set a daily spending limit', 'financial'),
('Challenge yourself to a no-spend day', 'financial'),
('Meal plan to save money', 'financial'),
('Make a shopping list before shopping', 'financial'),
('Use coupons or vouchers', 'financial'),
('Check for student discounts', 'financial'),
('Sign up for loyalty cards', 'financial'),
('Compare prices before buying', 'financial'),
('Wait 24 hours before a non-essential purchase', 'financial'),
('Unsubscribe from shopping emails', 'financial'),
('Delete shopping apps', 'financial'),
('Avoid impulse purchases', 'financial'),
('Buy generic brands instead of branded', 'financial'),
('Shop at budget supermarkets', 'financial'),
('Buy reduced items near closing time', 'financial'),
('Use a cashback app', 'financial'),
('Claim cashback on a purchase', 'financial'),
('Sell one item you don''t need', 'financial'),
('List something on a selling app', 'financial'),
('Take items to a charity shop', 'financial'),
('Donate for a tax receipt', 'financial'),
('Declutter and sell clothes', 'financial'),
('Sell old electronics', 'financial'),
('Trade in old devices', 'financial'),
('Recycle for cash', 'financial'),
('Return bottles for deposit', 'financial'),
('Look for free events in your area', 'financial'),
('Use the library instead of buying books', 'financial'),
('Borrow instead of buying', 'financial'),
('Rent instead of purchasing', 'financial'),
('Buy second-hand', 'financial'),
('Shop at charity shops', 'financial'),
('Use free trials wisely', 'financial'),
('Cancel before free trial ends', 'financial'),
('Set a reminder for trial expiry', 'financial'),
('Review all subscriptions', 'financial'),
('Downgrade a subscription', 'financial'),
('Share a subscription with family', 'financial'),
('Use free alternatives to paid apps', 'financial'),
('Find free entertainment', 'financial'),
('Watch free content online', 'financial'),
('Use free streaming services', 'financial'),
('Listen to free music', 'financial'),
('Access free courses online', 'financial'),
('Use free educational resources', 'financial'),
('Apply for hardship funds', 'financial'),
('Research grants you might qualify for', 'financial'),
('Apply for a crisis loan', 'financial'),
('Contact a food bank if needed', 'financial'),
('Find free meals in your area', 'financial'),
('Use a community fridge', 'financial'),
('Access free toiletries programs', 'financial'),
('Get free period products', 'financial'),
('Find free clothing programs', 'financial'),
('Access free furniture schemes', 'financial'),
('Get help with white goods', 'financial'),
('Apply for a budgeting loan', 'financial'),
('Research debt advice services', 'financial'),
('Contact StepChange for debt help', 'financial'),
('Call National Debtline', 'financial'),
('Speak to Citizens Advice about debt', 'financial'),
('Make a list of all debts', 'financial'),
('Note interest rates on debts', 'financial'),
('Prioritize which debts to pay first', 'financial'),
('Pay priority debts first', 'financial'),
('Contact creditors about payment plans', 'financial'),
('Request a payment holiday', 'financial'),
('Negotiate lower payments', 'financial'),
('Ask about debt write-off schemes', 'financial'),
('Research debt consolidation', 'financial'),
('Consider a Debt Relief Order', 'financial'),
('Look into an IVA', 'financial'),
('Understand bankruptcy options', 'financial'),
('Never ignore debt letters', 'financial'),
('Open all your mail', 'financial'),
('Respond to creditor letters', 'financial'),
('Keep copies of all correspondence', 'financial'),
('Document all phone calls', 'financial'),
('Request written confirmation', 'financial'),
('Know your rights with debt collectors', 'financial'),
('Don''t let bailiffs in without checking', 'financial'),
('Verify bailiff credentials', 'financial'),
('Know what bailiffs can and can''t take', 'financial'),
('Get advice before dealing with bailiffs', 'financial'),
('Challenge unfair debt collection', 'financial'),
('Report harassment by creditors', 'financial'),
('Complain to the Financial Ombudsman', 'financial'),
('Know you have rights as a consumer', 'financial'),
('Research consumer protection laws', 'financial'),
('Join a credit union', 'financial'),
('Avoid payday loans', 'financial'),
('Never borrow from loan sharks', 'financial'),
('Report illegal money lending', 'financial'),
('Seek help for gambling problems', 'financial'),
('Block gambling websites', 'financial'),
('Self-exclude from betting', 'financial'),
('Talk to someone about money worries', 'financial'),
('Join a money management group', 'financial'),
('Attend a free financial workshop', 'financial'),
('Read one article about personal finance', 'financial'),
('Watch a video about budgeting', 'financial'),
('Learn about the 50/30/20 rule', 'financial'),
('Understand needs vs wants', 'financial'),
('Calculate your net worth', 'financial'),
('Set one financial goal', 'financial'),
('Break a financial goal into steps', 'financial'),
('Celebrate a financial milestone', 'financial'),
('Acknowledge your financial progress', 'financial'),
('Forgive yourself for money mistakes', 'financial'),
('Learn from past financial errors', 'financial'),
('Don''t compare your finances to others', 'financial'),
('Remember everyone''s situation is different', 'financial'),
('Be proud of managing your money', 'financial'),
('Recognize that asking for help is strong', 'financial');

-- Household wins (200 items)
INSERT INTO small_wins (title, category) VALUES
('Wash 5 dishes', 'household'),
('Clear the kitchen sink', 'household'),
('Wipe down the kitchen counter', 'household'),
('Take out the rubbish', 'household'),
('Empty one bin', 'household'),
('Replace a full bin bag', 'household'),
('Wipe the kitchen table', 'household'),
('Sweep the kitchen floor', 'household'),
('Mop one small area', 'household'),
('Clean the hob', 'household'),
('Wipe the microwave inside', 'household'),
('Clean the kettle', 'household'),
('Descale the kettle', 'household'),
('Wipe the toaster', 'household'),
('Empty the crumb tray', 'household'),
('Clean the fridge door', 'household'),
('Throw out expired food', 'household'),
('Wipe one fridge shelf', 'household'),
('Organize the fridge', 'household'),
('Defrost the freezer', 'household'),
('Organize the freezer', 'household'),
('Label frozen items with dates', 'household'),
('Clean the oven (or just the door)', 'household'),
('Wipe oven spills', 'household'),
('Clean the extractor fan', 'household'),
('Wash the dish rack', 'household'),
('Clean the sink drain', 'household'),
('Unclog a slow drain', 'household'),
('Organize under the sink', 'household'),
('Throw out old cleaning products', 'household'),
('Restock cleaning supplies', 'household'),
('Buy washing up liquid', 'household'),
('Get more bin bags', 'household'),
('Stock up on sponges', 'household'),
('Wash one load of laundry', 'household'),
('Hang up wet laundry', 'household'),
('Fold clean laundry', 'household'),
('Put away clean clothes', 'household'),
('Sort laundry into colors', 'household'),
('Treat a stain', 'household'),
('Hand wash delicates', 'household'),
('Clean the washing machine', 'household'),
('Run a maintenance wash', 'household'),
('Clear the lint filter', 'household'),
('Empty the tumble dryer', 'household'),
('Iron one item', 'household'),
('Steam wrinkled clothes', 'household'),
('Hang clothes to prevent wrinkles', 'household'),
('Organize your wardrobe', 'household'),
('Donate clothes you don''t wear', 'household'),
('Vacuum one room', 'household'),
('Vacuum under furniture', 'household'),
('Empty the vacuum cleaner', 'household'),
('Change the vacuum bag', 'household'),
('Dust one surface', 'household'),
('Dust picture frames', 'household'),
('Dust light fixtures', 'household'),
('Wipe down skirting boards', 'household'),
('Clean light switches', 'household'),
('Wipe door handles', 'household'),
('Clean mirrors', 'household'),
('Wash windows', 'household'),
('Wipe window sills', 'household'),
('Clean blinds', 'household'),
('Wash curtains', 'household'),
('Shake out rugs', 'household'),
('Vacuum rugs', 'household'),
('Spot clean carpet stains', 'household'),
('Rearrange furniture', 'household'),
('Declutter one drawer', 'household'),
('Organize one shelf', 'household'),
('Tidy one surface', 'household'),
('Clear the coffee table', 'household'),
('Organize the TV stand', 'household'),
('Tidy cables and wires', 'household'),
('Dust electronics', 'household'),
('Clean your keyboard', 'household'),
('Wipe your phone screen', 'household'),
('Clean your laptop', 'household'),
('Organize computer files', 'household'),
('Delete old files', 'household'),
('Empty the recycle bin', 'household'),
('Back up important files', 'household'),
('Update software', 'household'),
('Charge your devices', 'household'),
('Organize charging cables', 'household'),
('Clean the bathroom sink', 'household'),
('Scrub the toilet', 'household'),
('Clean the toilet brush', 'household'),
('Wipe the bathroom mirror', 'household'),
('Clean the shower', 'household'),
('Scrub the bathtub', 'household'),
('Clean shower doors', 'household'),
('Wash the shower curtain', 'household'),
('Unclog the shower drain', 'household'),
('Remove hair from the drain', 'household'),
('Descale the showerhead', 'household'),
('Clean bathroom tiles', 'household'),
('Scrub grout', 'household'),
('Wipe down bathroom surfaces', 'household'),
('Clean the bathroom floor', 'household'),
('Wash bathroom mats', 'household'),
('Replace the toilet roll', 'household'),
('Restock toilet paper', 'household'),
('Refill soap dispensers', 'household'),
('Replace hand towels', 'household'),
('Wash towels', 'household'),
('Organize bathroom cabinets', 'household'),
('Throw out expired toiletries', 'household'),
('Throw out expired medications', 'household'),
('Organize your medicine cabinet', 'household'),
('Restock first aid supplies', 'household'),
('Check smoke alarm batteries', 'household'),
('Test smoke alarms', 'household'),
('Check carbon monoxide detector', 'household'),
('Replace detector batteries', 'household'),
('Check fire extinguisher', 'household'),
('Know your fire escape route', 'household'),
('Unblock a fire exit', 'household'),
('Check door locks work', 'household'),
('Check window locks', 'household'),
('Test your door chain', 'household'),
('Install a door viewer', 'household'),
('Improve home security', 'household'),
('Report a repair to landlord', 'household'),
('Take photos of disrepair', 'household'),
('Document maintenance issues', 'household'),
('Follow up on repair requests', 'household'),
('Know what landlord must fix', 'household'),
('Know what you must fix as tenant', 'household'),
('Change a lightbulb', 'household'),
('Reset a tripped fuse', 'household'),
('Bleed a radiator', 'household'),
('Adjust radiator valves', 'household'),
('Unblock a sink', 'household'),
('Fix a dripping tap', 'household'),
('Tighten loose screws', 'household'),
('Oil squeaky hinges', 'household'),
('Fix a stuck drawer', 'household'),
('Tighten loose handles', 'household'),
('Replace worn washers', 'household'),
('Patch a small hole in the wall', 'household'),
('Touch up paint', 'household'),
('Caulk gaps', 'household'),
('Weather-strip doors', 'household'),
('Insulate windows', 'household'),
('Close curtains to keep heat in', 'household'),
('Open windows to air out rooms', 'household'),
('Let fresh air in for 10 minutes', 'household'),
('Open blinds for natural light', 'household'),
('Turn off lights when leaving a room', 'household'),
('Unplug devices not in use', 'household'),
('Switch to energy-saving bulbs', 'household'),
('Turn down the thermostat by 1 degree', 'household'),
('Only boil water you need', 'household'),
('Take shorter showers', 'household'),
('Turn off taps while brushing teeth', 'household'),
('Fix leaky taps', 'household'),
('Report water leaks', 'household'),
('Insulate your hot water tank', 'household'),
('Wash full loads of laundry', 'household'),
('Use eco settings on appliances', 'household'),
('Air dry clothes instead of tumble drying', 'household'),
('Defrost food in the fridge overnight', 'household'),
('Keep fridge and freezer full', 'household'),
('Don''t leave fridge door open', 'household'),
('Clean fridge coils', 'household'),
('Check fridge temperature', 'household'),
('Organize your pantry', 'household'),
('Check for pantry pests', 'household'),
('Store food in airtight containers', 'household'),
('Label containers with dates', 'household'),
('Rotate food stock (first in, first out)', 'household'),
('Plan meals around what you have', 'household'),
('Use up food before it expires', 'household'),
('Freeze food before it goes bad', 'household'),
('Compost food scraps', 'household'),
('Start a small herb garden', 'household'),
('Water your plants', 'household'),
('Remove dead leaves from plants', 'household'),
('Repot a plant', 'household'),
('Propagate a plant', 'household'),
('Clean plant leaves', 'household'),
('Move plants to better light', 'household'),
('Research plant care', 'household'),
('Buy a low-maintenance plant', 'household'),
('Enjoy having greenery in your home', 'household'),
('Open mail and sort it', 'household'),
('File important documents', 'household'),
('Shred junk mail', 'household'),
('Recycle paper and cardboard', 'household'),
('Take recycling out', 'household'),
('Rinse recyclables', 'household'),
('Flatten cardboard boxes', 'household'),
('Organize recycling bins', 'household'),
('Learn what can be recycled', 'household'),
('Reduce single-use plastics', 'household'),
('Use reusable bags', 'household'),
('Use reusable water bottles', 'household'),
('Use reusable coffee cups', 'household'),
('Switch to bar soap', 'household'),
('Use refillable containers', 'household'),
('Buy in bulk to reduce packaging', 'household'),
('Repair instead of replacing', 'household'),
('Upcycle old items', 'household'),
('Donate usable items', 'household'),
('Recycle electronics properly', 'household'),
('Dispose of batteries safely', 'household'),
('Take old paint to recycling center', 'household'),
('Properly dispose of chemicals', 'household'),
('Never pour chemicals down drains', 'household');

-- Social wins (200 items)
INSERT INTO small_wins (title, category) VALUES
('Text a friend', 'social'),
('Reply to a message', 'social'),
('Send a meme to someone', 'social'),
('React to a friend''s post', 'social'),
('Comment on someone''s photo', 'social'),
('Like a friend''s update', 'social'),
('Share something funny', 'social'),
('Send a voice note', 'social'),
('Make a phone call', 'social'),
('Answer the phone', 'social'),
('Call a family member', 'social'),
('Video call someone', 'social'),
('Wave at a neighbor', 'social'),
('Say hello to someone', 'social'),
('Smile at a stranger', 'social'),
('Hold the door for someone', 'social'),
('Say thank you', 'social'),
('Say please', 'social'),
('Apologize if you need to', 'social'),
('Forgive someone', 'social'),
('Give someone a compliment', 'social'),
('Tell someone you appreciate them', 'social'),
('Express gratitude', 'social'),
('Send a thank you message', 'social'),
('Write a thank you note', 'social'),
('Acknowledge someone''s help', 'social'),
('Recognize someone''s effort', 'social'),
('Celebrate someone''s achievement', 'social'),
('Congratulate someone', 'social'),
('Wish someone happy birthday', 'social'),
('Send a card', 'social'),
('Remember an important date', 'social'),
('Check in on someone', 'social'),
('Ask how someone is doing', 'social'),
('Really listen to the answer', 'social'),
('Give someone your full attention', 'social'),
('Put your phone away during conversation', 'social'),
('Make eye contact', 'social'),
('Nod to show you''re listening', 'social'),
('Ask follow-up questions', 'social'),
('Show interest in someone''s life', 'social'),
('Remember details someone shared', 'social'),
('Bring up something they mentioned before', 'social'),
('Validate someone''s feelings', 'social'),
('Empathize with someone', 'social'),
('Offer support', 'social'),
('Ask if someone needs help', 'social'),
('Offer to help with something specific', 'social'),
('Do a favor for someone', 'social'),
('Help carry something', 'social'),
('Give someone a lift', 'social'),
('Lend something to someone', 'social'),
('Share your food', 'social'),
('Offer your seat', 'social'),
('Let someone go ahead of you', 'social'),
('Be patient with someone', 'social'),
('Be kind to someone having a bad day', 'social'),
('Comfort someone who''s upset', 'social'),
('Offer a hug (if appropriate)', 'social'),
('Sit with someone who''s alone', 'social'),
('Include someone who''s left out', 'social'),
('Invite someone to join you', 'social'),
('Make plans with a friend', 'social'),
('Suggest a meetup', 'social'),
('Propose a specific time and place', 'social'),
('Follow through on plans', 'social'),
('Don''t cancel at the last minute', 'social'),
('Be on time', 'social'),
('Let someone know if you''re running late', 'social'),
('Apologize if you''re late', 'social'),
('Respect people''s time', 'social'),
('Keep your promises', 'social'),
('Do what you say you''ll do', 'social'),
('Be reliable', 'social'),
('Be honest', 'social'),
('Tell the truth', 'social'),
('Admit when you''re wrong', 'social'),
('Take responsibility', 'social'),
('Don''t make excuses', 'social'),
('Own your mistakes', 'social'),
('Learn from conflicts', 'social'),
('Resolve a disagreement', 'social'),
('Have a difficult conversation', 'social'),
('Express your needs', 'social'),
('Use "I" statements', 'social'),
('Avoid blaming language', 'social'),
('Stay calm during conflict', 'social'),
('Take a break if things get heated', 'social'),
('Come back to discuss when calm', 'social'),
('Compromise', 'social'),
('Find middle ground', 'social'),
('Agree to disagree', 'social'),
('Respect different opinions', 'social'),
('Don''t try to change people', 'social'),
('Accept people as they are', 'social'),
('Appreciate differences', 'social'),
('Learn from others', 'social'),
('Be open-minded', 'social'),
('Try to see things from another perspective', 'social'),
('Ask about someone''s culture', 'social'),
('Share about your background', 'social'),
('Try food from another culture', 'social'),
('Learn a few words in another language', 'social'),
('Attend a cultural event', 'social'),
('Celebrate diversity', 'social'),
('Challenge stereotypes', 'social'),
('Call out discrimination', 'social'),
('Stand up for someone', 'social'),
('Be an ally', 'social'),
('Educate yourself', 'social'),
('Acknowledge your privilege', 'social'),
('Use your voice for good', 'social'),
('Support marginalized voices', 'social'),
('Amplify others'' messages', 'social'),
('Share resources', 'social'),
('Donate to a cause', 'social'),
('Volunteer your time', 'social'),
('Help in your community', 'social'),
('Join a local group', 'social'),
('Attend a community event', 'social'),
('Support local businesses', 'social'),
('Shop at independent stores', 'social'),
('Leave a positive review', 'social'),
('Recommend a business to others', 'social'),
('Tip service workers', 'social'),
('Be polite to staff', 'social'),
('Don''t take frustrations out on workers', 'social'),
('Treat everyone with respect', 'social'),
('Be kind to people in service roles', 'social'),
('Thank delivery drivers', 'social'),
('Appreciate cleaners', 'social'),
('Acknowledge security staff', 'social'),
('Greet receptionists', 'social'),
('Be friendly to cashiers', 'social'),
('Chat with baristas', 'social'),
('Compliment someone''s work', 'social'),
('Recognize someone''s skills', 'social'),
('Encourage someone', 'social'),
('Believe in someone', 'social'),
('Support someone''s dreams', 'social'),
('Cheer someone on', 'social'),
('Be someone''s cheerleader', 'social'),
('Celebrate with someone', 'social'),
('Share in someone''s joy', 'social'),
('Be happy for others', 'social'),
('Don''t be jealous of others'' success', 'social'),
('Compliment instead of comparing', 'social'),
('Lift others up', 'social'),
('Don''t put others down', 'social'),
('Avoid gossip', 'social'),
('Don''t spread rumors', 'social'),
('Defend someone who''s not there', 'social'),
('Speak well of others', 'social'),
('Give people the benefit of the doubt', 'social'),
('Assume good intentions', 'social'),
('Don''t jump to conclusions', 'social'),
('Ask for clarification', 'social'),
('Communicate clearly', 'social'),
('Be direct but kind', 'social'),
('Say what you mean', 'social'),
('Mean what you say', 'social'),
('Be authentic', 'social'),
('Be yourself', 'social'),
('Don''t pretend to be someone you''re not', 'social'),
('Share your true feelings', 'social'),
('Be vulnerable', 'social'),
('Open up to someone', 'social'),
('Trust someone', 'social'),
('Let someone in', 'social'),
('Share something personal', 'social'),
('Tell someone your story', 'social'),
('Ask about someone''s story', 'social'),
('Show curiosity about people', 'social'),
('Get to know someone better', 'social'),
('Deepen a friendship', 'social'),
('Spend quality time with someone', 'social'),
('Have a meaningful conversation', 'social'),
('Talk about something important', 'social'),
('Discuss your values', 'social'),
('Share your goals', 'social'),
('Talk about your dreams', 'social'),
('Listen to someone''s dreams', 'social'),
('Support someone''s goals', 'social'),
('Help someone with their plans', 'social'),
('Collaborate on something', 'social'),
('Work together', 'social'),
('Be a team player', 'social'),
('Contribute to a group', 'social'),
('Participate in a discussion', 'social'),
('Share your ideas', 'social'),
('Listen to others'' ideas', 'social'),
('Build on someone''s suggestion', 'social'),
('Give credit where it''s due', 'social'),
('Acknowledge others'' contributions', 'social'),
('Share success with the team', 'social'),
('Celebrate group achievements', 'social'),
('Thank your team', 'social'),
('Appreciate collaboration', 'social'),
('Value different perspectives', 'social'),
('Learn from group work', 'social'),
('Enjoy social connection', 'social'),
('Appreciate your relationships', 'social'),
('Be grateful for friends', 'social'),
('Value your family', 'social'),
('Cherish your loved ones', 'social'),
('Tell people you love them', 'social'),
('Show affection', 'social'),
('Express care', 'social'),
('Demonstrate love', 'social'),
('Be there for someone', 'social'),
('Show up for people', 'social'),
('Be present', 'social'),
('Give your time', 'social'),
('Make someone a priority', 'social'),
('Put effort into relationships', 'social'),
('Nurture your connections', 'social'),
('Invest in friendships', 'social'),
('Maintain relationships', 'social'),
('Reach out regularly', 'social'),
('Don''t let friendships fade', 'social'),
('Reconnect with someone', 'social'),
('Reach out to an old friend', 'social'),
('Apologize for losing touch', 'social'),
('Forgive someone for losing touch', 'social'),
('Give people second chances', 'social'),
('Let go of grudges', 'social'),
('Move past conflicts', 'social'),
('Heal relationships', 'social'),
('Repair a friendship', 'social'),
('Make amends', 'social'),
('Seek forgiveness', 'social'),
('Offer forgiveness', 'social'),
('Let go of resentment', 'social'),
('Choose peace', 'social'),
('Choose connection', 'social'),
('Choose love', 'social'),
('Choose kindness', 'social'),
('Be the friend you want to have', 'social'),
('Treat others how you want to be treated', 'social');

-- Learning wins (100 items)
INSERT INTO small_wins (title, category) VALUES
('Read one page of a book', 'learning'),
('Read an article', 'learning'),
('Watch an educational video', 'learning'),
('Listen to a podcast episode', 'learning'),
('Learn one new word', 'learning'),
('Look up a word you don''t know', 'learning'),
('Use a new word in a sentence', 'learning'),
('Practice a language for 5 minutes', 'learning'),
('Learn to say hello in another language', 'learning'),
('Watch a documentary', 'learning'),
('Visit a museum (or virtual tour)', 'learning'),
('Read about history', 'learning'),
('Learn about a historical figure', 'learning'),
('Study a map', 'learning'),
('Learn about a country', 'learning'),
('Research a culture', 'learning'),
('Learn about a religion', 'learning'),
('Study philosophy', 'learning'),
('Read about science', 'learning'),
('Watch a science video', 'learning'),
('Learn about space', 'learning'),
('Study biology', 'learning'),
('Learn about animals', 'learning'),
('Research plants', 'learning'),
('Study the environment', 'learning'),
('Learn about climate change', 'learning'),
('Research sustainability', 'learning'),
('Learn about renewable energy', 'learning'),
('Study technology', 'learning'),
('Learn about computers', 'learning'),
('Practice typing', 'learning'),
('Learn a keyboard shortcut', 'learning'),
('Try a new software', 'learning'),
('Learn a new app', 'learning'),
('Watch a tutorial', 'learning'),
('Follow a how-to guide', 'learning'),
('Learn a new skill', 'learning'),
('Practice a skill', 'learning'),
('Take an online course', 'learning'),
('Complete one lesson', 'learning'),
('Do one exercise', 'learning'),
('Take notes', 'learning'),
('Review your notes', 'learning'),
('Make flashcards', 'learning'),
('Quiz yourself', 'learning'),
('Test your knowledge', 'learning'),
('Learn from mistakes', 'learning'),
('Try again after failing', 'learning'),
('Ask a question', 'learning'),
('Seek clarification', 'learning'),
('Research something you''re curious about', 'learning'),
('Follow your interests', 'learning'),
('Explore a new topic', 'learning'),
('Read about something unfamiliar', 'learning'),
('Challenge your assumptions', 'learning'),
('Question what you think you know', 'learning'),
('Be open to new information', 'learning'),
('Change your mind based on evidence', 'learning'),
('Admit you don''t know something', 'learning'),
('Say "I don''t know but I''ll find out"', 'learning'),
('Look something up', 'learning'),
('Fact-check information', 'learning'),
('Verify sources', 'learning'),
('Think critically', 'learning'),
('Analyze information', 'learning'),
('Compare different viewpoints', 'learning'),
('Consider multiple perspectives', 'learning'),
('Form your own opinion', 'learning'),
('Articulate your thoughts', 'learning'),
('Explain something to someone', 'learning'),
('Teach someone something', 'learning'),
('Share your knowledge', 'learning'),
('Help someone learn', 'learning'),
('Learn by teaching', 'learning'),
('Study with someone', 'learning'),
('Join a study group', 'learning'),
('Discuss what you''re learning', 'learning'),
('Debate ideas respectfully', 'learning'),
('Learn from others', 'learning'),
('Listen to experts', 'learning'),
('Read expert opinions', 'learning'),
('Follow educational accounts', 'learning'),
('Subscribe to learning channels', 'learning'),
('Join educational communities', 'learning'),
('Participate in forums', 'learning'),
('Ask questions online', 'learning'),
('Answer questions to help others', 'learning'),
('Share resources', 'learning'),
('Recommend learning materials', 'learning'),
('Create a reading list', 'learning'),
('Set a learning goal', 'learning'),
('Track your learning progress', 'learning'),
('Celebrate learning achievements', 'learning'),
('Acknowledge your growth', 'learning'),
('Reflect on what you''ve learned', 'learning'),
('Apply what you''ve learned', 'learning'),
('Use new knowledge', 'learning'),
('Practice new skills', 'learning'),
('Experiment with ideas', 'learning'),
('Try different approaches', 'learning'),
('Learn from experience', 'learning'),
('Reflect on experiences', 'learning'),
('Keep a learning journal', 'learning'),
('Document your learning journey', 'learning');

-- Health wins (100 items)
INSERT INTO small_wins (title, category) VALUES
('Drink a glass of water', 'health'),
('Drink 8 glasses of water today', 'health'),
('Carry a water bottle', 'health'),
('Eat a healthy breakfast', 'health'),
('Eat a vegetable', 'health'),
('Eat a piece of fruit', 'health'),
('Have a balanced meal', 'health'),
('Try a new healthy food', 'health'),
('Cook a meal from scratch', 'health'),
('Meal prep for tomorrow', 'health'),
('Pack a healthy lunch', 'health'),
('Bring healthy snacks', 'health'),
('Avoid skipping meals', 'health'),
('Eat regular meals', 'health'),
('Listen to your hunger cues', 'health'),
('Stop eating when full', 'health'),
('Eat mindfully', 'health'),
('Chew food thoroughly', 'health'),
('Reduce sugar intake', 'health'),
('Limit processed foods', 'health'),
('Choose whole grains', 'health'),
('Eat more fiber', 'health'),
('Include protein in meals', 'health'),
('Eat healthy fats', 'health'),
('Take a multivitamin', 'health'),
('Get vitamin D', 'health'),
('Spend time in sunlight', 'health'),
('Go for a walk', 'health'),
('Walk for 10 minutes', 'health'),
('Take the stairs', 'health'),
('Stand up and stretch', 'health'),
('Do 5 minutes of exercise', 'health'),
('Try a workout video', 'health'),
('Do some yoga', 'health'),
('Practice stretching', 'health'),
('Do strength exercises', 'health'),
('Go for a run', 'health'),
('Ride a bike', 'health'),
('Go swimming', 'health'),
('Play a sport', 'health'),
('Dance for exercise', 'health'),
('Try a new physical activity', 'health'),
('Move your body', 'health'),
('Be active for 30 minutes', 'health'),
('Exercise at your own pace', 'health'),
('Don''t compare your fitness to others', 'health'),
('Celebrate physical achievements', 'health'),
('Rest when you need to', 'health'),
('Take a rest day', 'health'),
('Allow recovery time', 'health'),
('Get 8 hours of sleep', 'health'),
('Go to bed at a regular time', 'health'),
('Wake up at a regular time', 'health'),
('Avoid screens before bed', 'health'),
('Create a bedtime routine', 'health'),
('Make your bedroom comfortable', 'health'),
('Keep bedroom cool and dark', 'health'),
('Use comfortable bedding', 'health'),
('Limit caffeine after 2pm', 'health'),
('Avoid alcohol before bed', 'health'),
('Don''t eat heavy meals late', 'health'),
('Relax before bedtime', 'health'),
('Try sleep meditation', 'health'),
('Use a sleep app', 'health'),
('Track your sleep', 'health'),
('Improve sleep hygiene', 'health'),
('Nap if you need to (20 min max)', 'health'),
('Brush teeth twice daily', 'health'),
('Floss daily', 'health'),
('Use mouthwash', 'health'),
('Visit the dentist', 'health'),
('Book a dental checkup', 'health'),
('See your GP', 'health'),
('Book a health checkup', 'health'),
('Get a health screening', 'health'),
('Check your blood pressure', 'health'),
('Monitor your health', 'health'),
('Take prescribed medications', 'health'),
('Set medication reminders', 'health'),
('Refill prescriptions', 'health'),
('Attend medical appointments', 'health'),
('Follow medical advice', 'health'),
('Ask your doctor questions', 'health'),
('Get a second opinion', 'health'),
('Research your symptoms', 'health'),
('Keep a symptom diary', 'health'),
('Track your health data', 'health'),
('Monitor chronic conditions', 'health'),
('Manage your condition', 'health'),
('Learn about your diagnosis', 'health'),
('Join a support group', 'health'),
('Connect with others with same condition', 'health'),
('Share your health journey', 'health'),
('Don''t suffer in silence', 'health'),
('Advocate for your health', 'health'),
('Speak up about symptoms', 'health'),
('Don''t minimize your pain', 'health'),
('Seek help when needed', 'health'),
('Call 111 for health advice', 'health'),
('Go to A&E if it''s an emergency', 'health'),
('Know when to seek urgent care', 'health');

-- Create RPC function to get daily small wins
CREATE OR REPLACE FUNCTION get_daily_small_wins(
  p_user_uuid text,
  p_count int DEFAULT 3
)
RETURNS TABLE (
  id bigint,
  title text,
  category text
) 
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_date_seed int;
  v_excluded_ids bigint[];
BEGIN
  -- Use current date as seed for deterministic selection
  v_date_seed := EXTRACT(EPOCH FROM CURRENT_DATE)::int;
  
  -- Get IDs of wins shown in last 30 days for this user
  SELECT ARRAY_AGG(small_win_id)
  INTO v_excluded_ids
  FROM user_small_wins_history
  WHERE user_uuid = p_user_uuid
    AND shown_at > CURRENT_DATE - INTERVAL '30 days';
  
  -- If no excluded IDs, initialize empty array
  IF v_excluded_ids IS NULL THEN
    v_excluded_ids := ARRAY[]::bigint[];
  END IF;
  
  -- Return random wins not shown recently, using date as seed
  RETURN QUERY
  SELECT sw.id, sw.title, sw.category
  FROM small_wins sw
  WHERE sw.id != ALL(v_excluded_ids)
  ORDER BY RANDOM()
  LIMIT p_count;
END;
$$;

-- Create function to record shown wins
CREATE OR REPLACE FUNCTION record_shown_wins(
  p_user_uuid text,
  p_win_ids bigint[]
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_win_id bigint;
BEGIN
  FOREACH v_win_id IN ARRAY p_win_ids
  LOOP
    INSERT INTO user_small_wins_history (user_uuid, small_win_id, shown_at)
    VALUES (p_user_uuid, v_win_id, CURRENT_TIMESTAMP);
  END LOOP;
END;
$$;

-- Grant permissions
GRANT SELECT ON small_wins TO anon, authenticated;
GRANT SELECT, INSERT ON user_small_wins_history TO anon, authenticated;
GRANT EXECUTE ON FUNCTION get_daily_small_wins TO anon, authenticated;
GRANT EXECUTE ON FUNCTION record_shown_wins TO anon, authenticated;
